// =============================================================================
// THE FEATURE MATRIX, LIFTED OUT OF FIFTEEN HAND-WRITTEN PAGES
// =============================================================================
// Each /vs/<slug> page used to carry its own ~490-line view.tsx, and inside it
// its own copy of this table. Fifteen copies of one component meant a design
// change had to be made fifteen times, and a corrected fact could be fixed on
// one page and stay wrong on the other fourteen.
//
// The rows were moved VERBATIM - copied as source text, never retyped - because
// 296 hand-written claims about other companies' products is exactly the kind
// of content that quietly degrades when transcribed.
//
// competitors.ts holds the narrative: pricing, contract, wins, friction. This
// holds the matrix. They are separate because they are edited for different
// reasons, at different times, from different sources.
//
// `true` renders a green check, `false` a red cross, and any STRING renders
// amber - tier-gated, structurally different, or a claim we could not confirm
// independently. That third state is doing most of the honest work here: it is
// what keeps these pages a comparison rather than an advert.
// =============================================================================

export interface FeatureRow {
  feature: string
  dialerseat: boolean | string
  competitor: boolean | string
}

export interface CompetitorFeatures {
  /** Prose above the table. Concedes what the competitor is genuinely good at. */
  lede: string
  rows: FeatureRow[]
}

export const COMPETITOR_FEATURES: Record<string, CompetitorFeatures> = {
  "3cx": {
    lede: "3CX is priced and built around business phone infrastructure \u2014 extensions, ring groups, video conferencing, a PBX for the whole office \u2014 licensed by simultaneous call capacity, not by seat. DialerSeat\u2122 is built for one job: running outbound sales campaigns, with lead lists, dispositions, compliance, and a dialer that speeds up or slows down per campaign. Neither product is trying to be the other.",
    rows: [
  { feature: 'Built for outbound sales campaigns', dialerseat: true, competitor: false },
  { feature: 'Lead lists with dispositions', dialerseat: true, competitor: false },
  { feature: 'Predictive dialer for cold outbound', dialerseat: true, competitor: false },
  { feature: 'Preview / power / progressive dialer', dialerseat: true, competitor: false },
  { feature: 'AMD voicemail filter always on', dialerseat: true, competitor: false },
  { feature: 'TCPA windows enforced server-side', dialerseat: true, competitor: false },
  { feature: 'Multiple scripts per campaign', dialerseat: true, competitor: false },
  { feature: 'Per-seat pricing, no capacity planning', dialerseat: true, competitor: false },
  { feature: 'SIP trunk / carrier included', dialerseat: true, competitor: false },
  { feature: 'Hosting decision required', dialerseat: false, competitor: true },
  { feature: 'General office PBX (extensions, ring groups)', dialerseat: false, competitor: true },
  { feature: 'Video conferencing / team chat', dialerseat: false, competitor: true },
  { feature: 'Public per-unit pricing', dialerseat: true, competitor: true },
  { feature: 'Weekly billing option', dialerseat: true, competitor: false },
  { feature: 'Works on phones + tablets (PWA install)', dialerseat: true, competitor: 'Softphone app' },
    ],
  },
  "aircall": {
    lede: "Aircall is a well-established, CRM-friendly business phone system, and its Power Dialer \u2014 confirmed directly from Aircall's own product content \u2014 is a genuine power dialer that queues and cycles leads automatically. The catch, sourced from Aircall's own blog and independently corroborated across multiple vendor-pricing analyses: that dialer sits on the Professional plan, $50/seat/month, not the advertised $30/seat Essentials entry. One G2 reviewer put it plainly \u2014 they signed up specifically for the power dialer, found it wasn't on the basic plan, and called the product \"unusable\" without the paid upgrade. DialerSeat\u2122 includes the dialer at the price you're quoted.",
    rows: [
  { feature: 'Public per-seat pricing', dialerseat: true, competitor: 'Numbers only on third-party blogs, not their own pricing page' },
  { feature: 'Self-serve signup, no demo required', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Weekly billing option', dialerseat: true, competitor: false },
  { feature: 'No annual contract required', dialerseat: true, competitor: 'Monthly costs ~33% more per seat' },
  { feature: 'Minimum seats required', dialerseat: false, competitor: '3-license minimum, every plan' },
  { feature: 'Seat price', dialerseat: '$35/wk, cancel anytime', competitor: '$30–$50/seat/mo by tier' },
  { feature: 'Power Dialer included in entry tier', dialerseat: true, competitor: false },
  { feature: 'Power Dialer requires tier upgrade', dialerseat: false, competitor: 'Professional tier, $50/seat/mo' },
  { feature: 'Salesforce integration requires tier upgrade', dialerseat: false, competitor: 'Professional tier required' },
  { feature: 'Live call monitoring / whisper', dialerseat: true, competitor: 'Professional tier required' },
  { feature: 'Predictive dialer', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Progressive dialer', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Preview dialer', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Per-campaign dialer mode', dialerseat: true, competitor: 'Not specified' },
  { feature: 'AMD voicemail filter included', dialerseat: true, competitor: 'Not specified' },
  { feature: 'TCPA windows enforced server-side', dialerseat: true, competitor: 'Not specified' },
  { feature: 'STIR/SHAKEN A-attestation', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Pricing negotiable / not fixed at list', dialerseat: false, competitor: 'Median buyer saves 23% off list (Vendr data)' },
  { feature: 'Public API + webhooks (any CRM)', dialerseat: true, competitor: true },
  { feature: 'Works on phones + tablets (PWA install)', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Lapsed-user data preservation', dialerseat: true, competitor: 'Not specified' },
    ],
  },
  "batchdialer": {
    lede: "BatchDialer lives inside the BatchLeads / PropStream ecosystem, real estate investors and wholesalers pulling skip-traced property lists and dialing them. If that is your business, their data pipeline is genuinely convenient and this page will not talk you out of it.",
    rows: [
  { feature: 'Per-seat cost', dialerseat: '$35/wk: no prepay', competitor: '$119–$249/mo ($95–$199 annual)' },
  { feature: 'Weekly billing', dialerseat: true, competitor: false },
  { feature: 'Best rate without a year commitment', dialerseat: true, competitor: false },
  { feature: 'Setup fee', dialerseat: '$0', competitor: '$0' },
  { feature: 'Simultaneous lines', dialerseat: 'Paced to real agent availability', competitor: '3 on Starter, 5 on Pro/Enterprise' },
  { feature: 'Dialer modes', dialerseat: '4 (Preview, Power, Progressive, Predictive)', competitor: 'Predictive + Preview' },
  { feature: 'Numbers included', dialerseat: 'Managed pool, no per-number fee', competitor: '10 on Starter, then ~$2 each' },
  { feature: 'Automatic number replacement', dialerseat: 'Every plan', competitor: 'Pro / Enterprise only' },
  { feature: 'Recording retention', dialerseat: 'Per-campaign, opt-in', competitor: '90 / 180 / 365 days by tier' },
  { feature: 'Answering-machine detection', dialerseat: true, competitor: true },
  { feature: 'DNC + litigator scrubbing', dialerseat: 'DNC honored', competitor: true },
  { feature: 'Multiple scripts per campaign', dialerseat: true, competitor: 'One script per campaign' },
  { feature: 'Live mid-call script switching', dialerseat: true, competitor: false },
  { feature: 'Calling window per lead timezone', dialerseat: 'Enforced server-side', competitor: 'Not published' },
  { feature: 'Whitelabel / your own brand', dialerseat: 'Manager+ $75/mo flat', competitor: false },
  { feature: 'Public API + webhooks', dialerseat: true, competitor: 'Zapier, API, PropStream, BatchLeads' },
  { feature: 'Full dialer on phone + tablet', dialerseat: 'PWA install', competitor: 'Desktop-focused' },
  { feature: 'Industry-agnostic', dialerseat: true, competitor: 'Real estate investor ecosystem' },
  { feature: 'Lead data', dialerseat: 'Bring your own, no markup', competitor: '$49–$119/mo add-on packages' },
    ],
  },
  "cloudtalk": {
    lede: "CloudTalk shows up at the top of nearly every \"best cold calling dialer\" roundup for 2026, and it's a genuinely solid, broad cloud communications platform with strong CRM integrations. The catch, confirmed directly from CloudTalk's own published add-on menu: the seat price gets you a phone system, not a dialer. Power Dialer is a further $15/user/month, Parallel Dialer (multi-line) is a further $39/user/month \u2014 both stacked on top of the base seat. DialerSeat\u2122 includes every dialer mode in the one price.",
    rows: [
  { feature: 'Public per-seat pricing', dialerseat: true, competitor: true },
  { feature: 'Self-serve signup, no demo required', dialerseat: true, competitor: true },
  { feature: 'Weekly billing option', dialerseat: true, competitor: false },
  { feature: 'No annual contract required', dialerseat: true, competitor: 'Monthly exists but costs 30–40% more' },
  { feature: 'Seat price', dialerseat: '$35/wk, cancel anytime', competitor: '$19–$49/mo by tier' },
  { feature: 'Power Dialer included in seat price', dialerseat: true, competitor: false },
  { feature: 'Power Dialer cost', dialerseat: 'Included', competitor: '+$15/seat/mo add-on' },
  { feature: 'Parallel/multi-line dialer cost', dialerseat: 'Included', competitor: '+$39/seat/mo add-on' },
  { feature: 'Predictive dialer', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Preview dialer', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Progressive dialer', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Per-campaign dialer mode', dialerseat: true, competitor: 'Not specified' },
  { feature: 'AMD voicemail filter included', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Multiple scripts per campaign', dialerseat: true, competitor: 'Not specified' },
  { feature: 'TCPA windows enforced server-side', dialerseat: true, competitor: 'Not specified' },
  { feature: 'STIR/SHAKEN A-attestation', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Pricing displayed in USD', dialerseat: true, competitor: 'Renders in EUR by default' },
  { feature: 'Public API + webhooks (any CRM)', dialerseat: true, competitor: true },
  { feature: 'Works on phones + tablets', dialerseat: 'Full dialer, same as desktop', competitor: 'App exists; dialer add-ons still apply' },
  { feature: 'Lapsed-user data preservation', dialerseat: true, competitor: 'Not specified' },
    ],
  },
  "convoso": {
    lede: "Convoso earns its reputation with high-volume outbound teams \u2014 four dialer modes, claimed 97% AMD accuracy, and dedicated caller ID reputation management (their \"Ignite\" tooling). It's built for contact centers with 20+ agents running custom-quoted, usage-billed campaigns. DialerSeat\u2122 offers the same four dialer modes at a flat, published price with no seat minimum \u2014 built for teams that want to start with one seat and grow, not commit to a call-center-scale contract up front.",
    rows: [
  { feature: 'Public per-seat pricing', dialerseat: true, competitor: false },
  { feature: 'Self-serve signup, no demo required', dialerseat: true, competitor: false },
  { feature: 'Weekly billing option', dialerseat: true, competitor: false },
  { feature: 'No annual contract required', dialerseat: true, competitor: 'Month-to-month exists, but priced above annual' },
  { feature: 'Per-seat cost', dialerseat: '$35/wk, cancel anytime', competitor: '$90+/mo, custom quote' },
  { feature: 'Minimum seat count', dialerseat: false, competitor: '~20 seats typical' },
  { feature: 'Setup fee', dialerseat: '$0', competitor: 'Not published' },
  { feature: 'Predictive dialer', dialerseat: true, competitor: true },
  { feature: 'Power dialer', dialerseat: true, competitor: true },
  { feature: 'Progressive dialer', dialerseat: true, competitor: true },
  { feature: 'Preview dialer', dialerseat: true, competitor: true },
  { feature: 'Per-campaign dialer mode', dialerseat: true, competitor: 'Not specified' },
  { feature: 'AMD voicemail filter', dialerseat: true, competitor: '"97% accuracy" (vendor claim)' },
  { feature: 'Multiple scripts per campaign', dialerseat: true, competitor: 'Not specified' },
  { feature: 'TCPA windows enforced server-side', dialerseat: true, competitor: true },
  { feature: 'STIR/SHAKEN A-attestation', dialerseat: true, competitor: true },
  { feature: 'Carrier fees billed separately from seat price', dialerseat: false, competitor: true },
  { feature: 'Public API + webhooks (any CRM)', dialerseat: true, competitor: true },
  { feature: 'Works on phones + tablets (PWA install)', dialerseat: true, competitor: 'Not found' },
  { feature: 'Lapsed-user data preservation', dialerseat: true, competitor: 'Not specified' },
    ],
  },
  "dialpad": {
    lede: "Dialpad shows up frequently in \"best dialer\" roundups, largely on the strength of its AI transcription and coaching tools. Worth knowing before you sign up: those roundups are usually describing Dialpad's AI features, not its dialer. The core Dialpad Connect phone plans (Standard $15, Pro $25, Enterprise $35 per user/month) don't include a power dialer at any tier \u2014 multiple independent pricing breakdowns confirm it, listing \"Power Dialer\" as available only inside the separate Dialpad Sell product line, itself starting around $39/user/month. DialerSeat\u2122 is one product with the dialer already in it.",
    rows: [
  { feature: 'Public per-seat pricing', dialerseat: true, competitor: true },
  { feature: 'Self-serve signup, no demo required', dialerseat: true, competitor: true },
  { feature: 'Weekly billing option', dialerseat: true, competitor: false },
  { feature: 'No annual contract required', dialerseat: true, competitor: 'Monthly billing costs more per seat' },
  { feature: 'Seat price (Dialpad Connect)', dialerseat: '$35/wk, cancel anytime', competitor: '$15–$35/mo by tier' },
  { feature: 'Power dialer included in Connect at any tier', dialerseat: true, competitor: false },
  { feature: 'Power dialer available at all', dialerseat: true, competitor: 'Separate product, Dialpad Sell, $39+/mo' },
  { feature: 'CRM integrations on entry tier', dialerseat: true, competitor: 'Standard tier lacks CRM sync; requires Pro' },
  { feature: 'Minimum seats on Pro tier', dialerseat: false, competitor: '3-user minimum' },
  { feature: 'Predictive dialer', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Progressive dialer', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Preview dialer', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Per-campaign dialer mode', dialerseat: true, competitor: 'Not specified' },
  { feature: 'AMD voicemail filter included', dialerseat: true, competitor: 'Not specified' },
  { feature: 'TCPA windows enforced server-side', dialerseat: true, competitor: 'Not specified' },
  { feature: 'STIR/SHAKEN A-attestation', dialerseat: true, competitor: 'Not specified' },
  { feature: '"Unlimited calling" without regional restriction', dialerseat: true, competitor: 'US/Canada only, per multiple reports' },
  { feature: 'SMS overage fees', dialerseat: false, competitor: '$0.008/message after 250, per reports' },
  { feature: 'Public API + webhooks (any CRM)', dialerseat: true, competitor: true },
  { feature: 'Works on phones + tablets (PWA install)', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Lapsed-user data preservation', dialerseat: true, competitor: 'Not specified' },
    ],
  },
  "five9": {
    lede: "Five9 is a market leader in enterprise contact-center-as-a-service. They serve large call centers with hundreds or thousands of seats, complex IVR routing, multi-channel engagement, and deep workforce management. That's a real product for a real audience. But for solo agents and small-to-mid sales teams that just need outbound dialing, it's overbuilt \u2014 and overpriced. DialerSeat\u2122 is the outbound dialer without the enterprise tax.",
    rows: [
  { feature: 'Per-seat cost', dialerseat: '$35/wk, cancel anytime', competitor: '$175–$325/mo, contract' },
  { feature: 'Weekly billing', dialerseat: true, competitor: false },
  { feature: 'Public per-seat pricing', dialerseat: true, competitor: false },
  { feature: 'Self-serve signup, no demo required', dialerseat: true, competitor: false },
  { feature: 'No annual contract required', dialerseat: true, competitor: false },
  { feature: 'First dial under 10 minutes', dialerseat: true, competitor: 'Weeks of onboarding typical' },
  { feature: 'Setup fee', dialerseat: '$0', competitor: 'Variable, often substantial' },
  { feature: 'Power dialer', dialerseat: true, competitor: true },
  { feature: 'Preview dialer', dialerseat: true, competitor: true },
  { feature: 'Progressive dialer', dialerseat: true, competitor: true },
  { feature: 'Predictive dialer (multi-line)', dialerseat: true, competitor: true },
  { feature: 'Per-campaign dialer mode', dialerseat: true, competitor: 'Configurable per-tenant' },
  { feature: 'AMD voicemail filter always on', dialerseat: true, competitor: true },
  { feature: 'Multiple scripts per campaign', dialerseat: true, competitor: 'Custom build' },
  { feature: 'Live mid-call script switching', dialerseat: true, competitor: false },
  { feature: 'TCPA windows enforced server-side', dialerseat: true, competitor: 'Partial' },
  { feature: 'All outbound numbers carrier-registered', dialerseat: true, competitor: 'Variable' },
  { feature: 'STIR/SHAKEN A-attestation', dialerseat: true, competitor: true },
  { feature: 'Public API + webhooks (any CRM)', dialerseat: true, competitor: true },
  { feature: 'Works on phones + tablets (PWA install)', dialerseat: true, competitor: false },
  { feature: 'Calendar-aligned analytics (Sun/1st)', dialerseat: true, competitor: false },
  { feature: 'Lapsed-user data preservation', dialerseat: true, competitor: false },
  { feature: 'Suited for solo / small teams', dialerseat: true, competitor: 'Enterprise-focused' },
    ],
  },
  "hookedcrm": {
    lede: "Hooked CRM's calling workspace, CRM platform, and Tacklebox AI product pages are genuinely strong on inbound call handling, automatic lead creation, AI-assisted notes, and supervisor tools like monitor, whisper, and barge. What none of their public pages describe is a named outbound dialing mode \u2014 no predictive, power, or progressive dialer terminology anywhere on their site, unlike every other dialer in this category. DialerSeat\u2122 is built specifically for outbound: four dialer modes, lead lists, and dispositions, all included.",
    rows: [
  { feature: 'Public per-seat pricing', dialerseat: true, competitor: true },
  { feature: 'Self-serve signup, no demo required', dialerseat: true, competitor: false },
  { feature: 'Weekly billing option', dialerseat: true, competitor: false },
  { feature: 'No annual contract required', dialerseat: true, competitor: true },
  { feature: 'Per-seat cost', dialerseat: '$35/wk, cancel anytime', competitor: '$129–$169/mo' },
  { feature: 'AI add-on stacks on top of seat price', dialerseat: false, competitor: '+$59–$79/seat' },
  { feature: 'Setup fee', dialerseat: '$0', competitor: 'Not published' },
  { feature: 'Named dialer modes (power/predictive/etc.)', dialerseat: 'Preview, Power, Progressive, Predictive', competitor: 'Not specified anywhere on their site' },
  { feature: 'Predictive dialer (multi-line)', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Per-campaign dialer mode', dialerseat: true, competitor: false },
  { feature: 'AMD voicemail filter always on', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Multiple scripts per campaign', dialerseat: true, competitor: false },
  { feature: 'Live mid-call script switching', dialerseat: true, competitor: false },
  { feature: 'TCPA windows enforced server-side', dialerseat: true, competitor: 'Not specified' },
  { feature: 'STIR/SHAKEN A-attestation', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Built-in CRM with lead profiles', dialerseat: true, competitor: true },
  { feature: 'AI-assisted call notes', dialerseat: false, competitor: 'Tacklebox AI add-on' },
  { feature: 'Live call monitor / whisper / barge', dialerseat: true, competitor: true },
  { feature: 'Per-minute call charges on top of seat price', dialerseat: false, competitor: 'From $0.042/min' },
  { feature: 'Per-number charges', dialerseat: false, competitor: 'From $4.60/mo' },
  { feature: 'Public API + webhooks (any CRM)', dialerseat: true, competitor: true },
  { feature: 'Works on phones + tablets (PWA install)', dialerseat: true, competitor: 'Not found' },
  { feature: 'Lapsed-user data preservation', dialerseat: true, competitor: 'Not specified' },
    ],
  },
  "justcall": {
    lede: "JustCall's $29/user/month Team plan is real and gets you unlimited calling, SMS, and 100+ CRM integrations \u2014 but power and predictive dialing aren't included at that price; you need the Pro tier ($49/user/month) or higher. JustCall also runs the sales dialer as a genuinely separate mobile app from its general calling app \u2014 their own help center flags the two aren't interchangeable. DialerSeat\u2122 is one app, one price, dialer modes included from the first seat.",
    rows: [
  { feature: 'Public per-seat pricing', dialerseat: true, competitor: true },
  { feature: 'Self-serve signup, no demo required', dialerseat: true, competitor: true },
  { feature: 'Weekly billing option', dialerseat: true, competitor: false },
  { feature: 'No annual contract required', dialerseat: true, competitor: 'Monthly exists but costs more' },
  { feature: 'Per-seat cost', dialerseat: '$35/wk, cancel anytime', competitor: '$19–$89/mo by tier' },
  { feature: 'Minimum seats on standard plans', dialerseat: false, competitor: '2-seat minimum' },
  { feature: 'Power/predictive dialer included in entry tier', dialerseat: true, competitor: false },
  { feature: 'Predictive dialer', dialerseat: true, competitor: 'Pro tier ($49+/mo) and up' },
  { feature: 'Power dialer', dialerseat: true, competitor: 'Pro tier ($49+/mo) and up' },
  { feature: 'Progressive dialer', dialerseat: true, competitor: true },
  { feature: 'Preview dialer', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Sales dialer and general calling in one app', dialerseat: true, competitor: 'Two separate apps' },
  { feature: 'HIPAA compliance available', dialerseat: 'Not specified', competitor: 'Business tier, 10-seat minimum' },
  { feature: 'Per-campaign dialer mode', dialerseat: true, competitor: 'Not specified' },
  { feature: 'TCPA windows enforced server-side', dialerseat: true, competitor: 'Not specified' },
  { feature: 'STIR/SHAKEN A-attestation', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Unlimited calling with no overage risk', dialerseat: true, competitor: 'Fair Usage Policy applies' },
  { feature: 'Public API + webhooks (any CRM)', dialerseat: true, competitor: true },
  { feature: 'Works on phones + tablets (PWA install)', dialerseat: true, competitor: true },
  { feature: 'Lapsed-user data preservation', dialerseat: true, competitor: 'Not specified' },
    ],
  },
  "kixie": {
    lede: "Kixie holds a strong 4.8/5 on G2 across 800+ reviews, and its local presence and CRM-embedded workflow are real strengths for HubSpot- and Salesforce-native teams. Worth knowing going in: Kixie doesn't offer predictive dialing by design \u2014 their own content frames Multi-line PowerCall as an alternative that avoids predictive dialing's abandoned-call risk, a legitimate compliance-minded choice, not a gap. What is a gap is price structure: multi-line dialing, AI voice detection, and full minute allotments each add cost on top of the entry tier. DialerSeat\u2122 includes predictive, power, progressive, and preview dialing in one flat price.",
    rows: [
  { feature: 'Public per-seat pricing', dialerseat: true, competitor: false },
  { feature: 'Self-serve signup, no demo required', dialerseat: true, competitor: 'Free trial exists; full pricing requires sales' },
  { feature: 'Weekly billing option', dialerseat: true, competitor: false },
  { feature: 'No annual contract required', dialerseat: true, competitor: 'Billed quarterly; Trustpilot reviewers report lock-in at renewal' },
  { feature: 'Per-seat cost', dialerseat: '$35/wk, cancel anytime', competitor: '$35\u2013$95+/mo by tier' },
  { feature: 'Multi-line dialing included in base price', dialerseat: true, competitor: 'Requires PowerDialer tier, $95+/mo' },
  { feature: 'Predictive dialer', dialerseat: true, competitor: false },
  { feature: 'Power dialer', dialerseat: true, competitor: true },
  { feature: 'Progressive dialer', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Preview dialer', dialerseat: true, competitor: 'Not specified' },
  { feature: 'AI voice/answering-machine detection', dialerseat: true, competitor: '+$30/mo add-on' },
  { feature: 'Per-campaign dialer mode', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Multiple scripts per campaign', dialerseat: true, competitor: 'Not specified' },
  { feature: 'TCPA windows enforced server-side', dialerseat: true, competitor: 'Basic DNC tool only' },
  { feature: 'STIR/SHAKEN A-attestation', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Public API + webhooks (any CRM)', dialerseat: true, competitor: true },
  { feature: 'Works on phones + tablets', dialerseat: 'Full dialer, same as desktop', competitor: 'Native app, 2.05/5 on Android' },
  { feature: 'Lapsed-user data preservation', dialerseat: true, competitor: 'Not specified' },
    ],
  },
  "mojo": {
    lede: "Mojo Dialer ($149/mo with the mandatory Agent Access fee) gives you their 3-line dialer plus a real-estate-tuned interface and integrations. Their Single Line Dialer runs $99\u2013109/mo with that same fee and drops multi-line entirely. The product is solid but its DNA is real estate prospecting \u2014 neighborhood searches, FSBO/expired tools, MLS integrations. DialerSeat\u2122 is built for any outbound team in any industry, for $35/week, cancel anytime.",
    rows: [
  { feature: 'Per-seat cost', dialerseat: '$35/wk, cancel anytime', competitor: '$99–$149/mo + mandatory fee' },
  { feature: 'Weekly billing', dialerseat: true, competitor: false },
  { feature: 'Self-serve signup', dialerseat: true, competitor: true },
  { feature: 'No annual contract', dialerseat: true, competitor: true },
  { feature: 'Setup fee', dialerseat: '$0', competitor: '$0' },
  { feature: 'Triple-line dialer', dialerseat: '4 modes (Preview, Power, Progressive, Predictive)', competitor: '3-line (Mojo Dialer)' },
  { feature: 'Single-line dialer', dialerseat: 'Preview mode, included', competitor: 'Single Line Dialer, $89–99/mo + $10/mo Agent Access' },
  { feature: 'AMD voicemail filter always on', dialerseat: true, competitor: 'Voicemail drop only' },
  { feature: 'Multiple scripts per campaign', dialerseat: true, competitor: 'Scripts feature' },
  { feature: 'Live mid-call script switching', dialerseat: true, competitor: false },
  { feature: 'TCPA windows enforced server-side', dialerseat: true, competitor: 'Partial' },
  { feature: 'All outbound numbers carrier-registered', dialerseat: true, competitor: 'Variable' },
  { feature: 'STIR/SHAKEN A-attestation', dialerseat: true, competitor: 'Variable' },
  { feature: 'Public API + webhooks (any CRM)', dialerseat: true, competitor: 'Real estate CRM focus' },
  { feature: 'Works on phones + tablets (PWA install)', dialerseat: true, competitor: 'Desktop-focused' },
  { feature: 'Industry-agnostic', dialerseat: true, competitor: 'Real estate niche' },
  { feature: 'Calendar-aligned analytics (Sun/1st)', dialerseat: true, competitor: false },
  { feature: 'Lapsed-user data preservation', dialerseat: true, competitor: false },
  { feature: 'Modern UI', dialerseat: true, competitor: 'Legacy real-estate-focused UI' },
    ],
  },
  "orum": {
    lede: "Credit where due: Orum&apos;s AI-driven parallel dialing \u2014 up to 5: 10 lines at once \u2014 is a real, effective way to increase raw call volume for teams that can afford it. But it comes at a reported $250 to $800 per user per month, annual billing only, a 3-seat minimum, and pricing you can only get by requesting a demo. Reviewers also consistently flag a 1–2 second connection lag when a parallel-dialed call bridges to a rep, and numbers getting flagged &ldquo;Spam Likely&rdquo; over time. DialerSeat\u2122 is self-serve, published pricing, one seat minimum, and every dialer mode included from day one.",
    rows: [
  { feature: 'Public per-seat pricing', dialerseat: true, competitor: 'Request-a-quote only' },
  { feature: 'Self-serve signup, no demo required', dialerseat: true, competitor: false },
  { feature: 'Weekly billing option', dialerseat: true, competitor: false },
  { feature: 'Annual contract required', dialerseat: false, competitor: true },
  { feature: 'Per-seat cost', dialerseat: '$35/wk, cancel anytime', competitor: '~$250–$800/mo, billed annually' },
  { feature: 'Seat minimum', dialerseat: '1', competitor: '3 (~$9,000/yr floor)' },
  { feature: 'Dialer modes included in base price', dialerseat: true, competitor: 'Power dialer only; parallel tier costs more' },
  { feature: 'Multi-line / parallel dialing', dialerseat: 'Triple-line + true Predictive mode', competitor: '5–10 lines (AI parallel dialing)' },
  { feature: 'Connection lag on answer', dialerseat: 'Not applicable at triple-line', competitor: 'Widely reported 1–2 sec lag on parallel tier' },
  { feature: 'AMD / voicemail filtering', dialerseat: true, competitor: true },
  { feature: 'AI call coaching / review', dialerseat: 'Not specified', competitor: '$50–200/mo add-on' },
  { feature: 'Implementation / onboarding fee', dialerseat: '$0', competitor: 'Reported $1,000–$5,000+' },
  { feature: 'TCPA windows enforced server-side', dialerseat: true, competitor: 'Not specified' },
  { feature: 'STIR/SHAKEN A-attestation + carrier registration', dialerseat: true, competitor: 'Not specified' },
  { feature: 'Industry-agnostic', dialerseat: true, competitor: 'B2B SDR / sales-team focus' },
  { feature: 'Public API + webhooks (any CRM)', dialerseat: true, competitor: 'Native Salesforce/HubSpot/Outreach sync' },
  { feature: 'Works on phones + tablets (PWA install)', dialerseat: true, competitor: 'Not specified' },
  { feature: 'First dial after signup', dialerseat: 'Under 10 minutes', competitor: 'Demo + sales process first' },
    ],
  },
  "phoneburner": {
    lede: "PhoneBurner is deliberately single-line: agents dial through a list one at a time with voicemail drop and click-to-dial. That's a feature for solo agents who want maximum control. It's a limitation for teams that want predictive multi-line dialing on high-volume cold lists. DialerSeat\u2122 gives you all four modes \u2014 Preview, Power, Progressive, Predictive \u2014 configurable per campaign.",
    rows: [
  { feature: 'Per-seat cost', dialerseat: '$35/wk, cancel anytime', competitor: '$165+/mo, contract for less' },
  { feature: 'Weekly billing', dialerseat: true, competitor: false },
  { feature: 'Self-serve signup', dialerseat: true, competitor: true },
  { feature: 'No annual contract', dialerseat: true, competitor: true },
  { feature: 'Setup fee', dialerseat: '$0', competitor: '$0' },
  { feature: 'Single-line dialer', dialerseat: true, competitor: true },
  { feature: 'Multi-line predictive dialing', dialerseat: '4 modes incl. predictive', competitor: 'Single-line philosophy' },
  { feature: 'AMD voicemail filter always on', dialerseat: true, competitor: 'Voicemail drop' },
  { feature: 'Multiple scripts per campaign', dialerseat: true, competitor: 'Single script' },
  { feature: 'Live mid-call script switching', dialerseat: true, competitor: false },
  { feature: 'Per-campaign dialer mode', dialerseat: true, competitor: false },
  { feature: 'TCPA windows enforced server-side', dialerseat: true, competitor: 'Partial' },
  { feature: 'All outbound numbers carrier-registered', dialerseat: true, competitor: 'Variable' },
  { feature: 'STIR/SHAKEN A-attestation', dialerseat: true, competitor: 'Variable' },
  { feature: 'Public API + webhooks (any CRM)', dialerseat: true, competitor: true },
  { feature: 'Works on phones + tablets (PWA install)', dialerseat: true, competitor: 'Desktop-focused' },
  { feature: 'Calendar-aligned analytics (Sun/1st)', dialerseat: true, competitor: false },
  { feature: 'Lapsed-user data preservation', dialerseat: true, competitor: false },
    ],
  },
  "readymode": {
    lede: "ReadyMode has been a fixture of the outbound dialer category for years. Their core dialer works well. Where they fall down is delivery model \u2014 opaque pricing, multi-month contracts, setup fees, legacy UI that takes hours to learn. DialerSeat\u2122 keeps the dialer quality and strips the friction.",
    rows: [
  { feature: 'Public per-seat pricing', dialerseat: true, competitor: false },
  { feature: 'Self-serve signup, no demo required', dialerseat: true, competitor: false },
  { feature: 'Weekly billing option', dialerseat: true, competitor: false },
  { feature: 'No annual contract required', dialerseat: true, competitor: false },
  { feature: 'Per-seat cost', dialerseat: '$35/wk, cancel anytime', competitor: '$199+/mo, contract' },
  { feature: 'Setup fee', dialerseat: '$0', competitor: '$0–$2,000' },
  { feature: 'Power dialer', dialerseat: true, competitor: true },
  { feature: 'Preview dialer', dialerseat: true, competitor: true },
  { feature: 'Progressive dialer', dialerseat: true, competitor: true },
  { feature: 'Predictive dialer (multi-line)', dialerseat: true, competitor: true },
  { feature: 'Per-campaign dialer mode', dialerseat: true, competitor: false },
  { feature: 'AMD voicemail filter always on', dialerseat: true, competitor: 'Inconsistent' },
  { feature: 'Multiple scripts per campaign', dialerseat: true, competitor: false },
  { feature: 'Live mid-call script switching', dialerseat: true, competitor: false },
  { feature: 'TCPA windows enforced server-side', dialerseat: true, competitor: 'Partial' },
  { feature: 'All outbound numbers carrier-registered', dialerseat: true, competitor: 'Inconsistent' },
  { feature: 'STIR/SHAKEN A-attestation', dialerseat: true, competitor: 'Variable' },
  { feature: 'Public API + webhooks (any CRM)', dialerseat: true, competitor: false },
  { feature: 'Works on phones + tablets (PWA install)', dialerseat: true, competitor: false },
  { feature: 'Calendar-aligned analytics (Sun/1st)', dialerseat: true, competitor: false },
  { feature: 'Lapsed-user data preservation', dialerseat: true, competitor: false },
  { feature: 'Modern UI, no learning curve', dialerseat: true, competitor: 'Legacy interface' },
    ],
  },
  "wavv": {
    lede: "WAVV is a legitimate dialer with a real trial and real month-to-month billing \u2014 this isn't the \"opaque enterprise pricing\" story. Where the two products diverge is structure: WAVV splits its dialer into three priced tiers, so the calling speed you get depends on which plan you're willing to pay for. DialerSeat\u2122 doesn't tier the dialer \u2014 every seat gets every mode.",
    rows: [
  { feature: 'Public per-seat pricing', dialerseat: true, competitor: true },
  { feature: 'Every dialer mode at one price', dialerseat: true, competitor: false },
  { feature: 'Weekly billing option', dialerseat: true, competitor: false },
  { feature: 'No annual contract required', dialerseat: true, competitor: true },
  { feature: 'Per-number fee', dialerseat: '$0 (unlimited)', competitor: '$1/mo per number' },
  { feature: 'Free trial', dialerseat: false, competitor: '7 days' },
  { feature: 'Power dialer', dialerseat: true, competitor: true },
  { feature: 'Preview dialer', dialerseat: true, competitor: true },
  { feature: 'Predictive dialer (multi-line)', dialerseat: true, competitor: 'Top tier only' },
  { feature: 'Per-campaign dialer mode', dialerseat: true, competitor: false },
  { feature: 'AMD voicemail filter always on', dialerseat: true, competitor: 'Inconsistent' },
  { feature: 'Multiple scripts per campaign', dialerseat: true, competitor: false },
  { feature: 'Live mid-call script switching', dialerseat: true, competitor: false },
  { feature: 'TCPA windows enforced server-side', dialerseat: true, competitor: 'Partial' },
  { feature: 'STIR/SHAKEN A-attestation', dialerseat: true, competitor: 'Variable' },
  { feature: 'Public API + webhooks (any CRM)', dialerseat: true, competitor: false },
  { feature: 'Works on phones + tablets', dialerseat: 'Same app, any device (PWA)', competitor: 'Separate companion app' },
  { feature: 'Lapsed-user data preservation', dialerseat: true, competitor: false },
    ],
  },
}

export function featuresFor(slug: string): CompetitorFeatures | null {
  return COMPETITOR_FEATURES[slug] ?? null
}
